### ISSUE TITLE
error react-native

### ISSUE THREAD

**Issue by pascal-maker** [gagigante/react-native-be-real#2]
None of these files exist:
  * src/screens/FriendsFeed(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * src/screens/FriendsFeed/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  4 | import {TouchableOpacity, Text, View} from 'react-native';
  5 |
> 6 | import {FriendsFeed} from '../screens/FriendsFeed';
    |                            ^
  7 | import {Settings} from '../screens/Settings';

**Comment by gagigante** [comment]
thanks for submit this issue. I'am working on it

**Comment by gagigante** [comment]
I had forgotten to include some files in the commit
